config/routes.rb
Rails.application.routes.draw do
  get 'genre_display', to:"genre_display#new"

  get '/play',   to:'genre_display#show'
  post '/play',  to:'genre_display#check'

  resources :leaderboards
  resources :questions
  resources :sub_genres
  resources :genres
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: "registrations"}

  root 'home#index'

  post '/questions/:id' => 'questions#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :sub_genre
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
      @questions = Question.all
    #   if current_user.admin == true
    #       @questions = Question.all
    #   else
    #       redirect_to root_path
    #   end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    #   if current_user.admin == true
    #   else
    #       redirect_to root_path
    #   end
  end

  # GET /questions/new
  def new
    if current_user.admin == true
        @question = Question.new
    else
        redirect_to root_path
    end
  end

  # GET /questions/1/edit
  def edit
      if current_user.admin == true
      else
          redirect_to root_path
      end
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
      a=''
      if(params[:Opta])
        a+='Opta'
        print("ok1\n\n\n")
      end
      if(params[:Optb])
        a+='Optb'
        print("ok2\n\n\n")
      end
      if(params[:Optc])
        a+='Optc'
        print("ok3\n\n\n")
      end
      if(params[:Optd])
        a+='Optd'
        print("ok4\n\n\n")
      end
      if(a == @question.answer)
          print("yes\n\n\n")
      else
          print("no\n\n\n")
      end
      redirect_to '/questions/#{params[:id]}'
    #   if a == @question.answer
    #       respond_to do |format|
    #           if @question.update(question_params)
    #               format.html { redirect_to @questions, notice: 'Question was successfully updated.' }
    #               format.json { render :show, status: :ok, location: @questions }
    #           else
    #               format.html { render :edit }
    #               format.json { render json: @question.errors, status: :unprocessable_entity }
    #           end
    #       end
    #   end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:number, :ques, :optA, :optB, :optC, :optD, :answer, :sub_genre_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :question_number %>
  </div>

  <div class="field">
    <%= form.label :ques %>
    <%= form.text_field :ques, id: :question_ques %>
  </div>

  <div class="field">
    <%= form.label :optA %>
    <%= form.text_field :optA, id: :question_optA %>
  </div>

  <div class="field">
    <%= form.label :optB %>
    <%= form.text_field :optB, id: :question_optB %>
  </div>

  <div class="field">
    <%= form.label :optC %>
    <%= form.text_field :optC, id: :question_optC %>
  </div>

  <div class="field">
    <%= form.label :optD %>
    <%= form.text_field :optD, id: :question_optD %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :question_answer %>
  </div>

  <div class="field">
    <%= form.label :sub_genre_id %>
    <%= form.text_field :sub_genre_id, id: :question_sub_genre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table border=1>
  <thead style="text-align:center;">
    <tr>
      <th>Number</th>
      <th>Ques</th>
      <th>Opta</th>
      <th>Optb</th>
      <th>Optc</th>
      <th>Optd</th>
      <th>Sub genre</th>
      <th>Genre</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody style="text-align: center;">
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.number %></td>
        <td><%= question.ques %></td>
        <td><%= question.optA %></td>
        <td><%= question.optB %></td>
        <td><%= question.optC %></td>
        <td><%= question.optD %></td>
        <td><%= question.sub_genre.subgenrename %></td>
        <td><%= question.sub_genre.genre.genrename %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% if current_user.admin == true %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @question.number %>
</p>

<p>
  <strong>Ques:</strong>
  <%= @question.ques %>
</p>

<p>
  <strong>Opta:</strong>
  <%= @question.optA %>
</p>

<p>
  <strong>Optb:</strong>
  <%= @question.optB %>
</p>

<p>
  <strong>Optc:</strong>
  <%= @question.optC %>
</p>

<p>
  <strong>Optd:</strong>
  <%= @question.optD %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Sub genre:</strong>
  <%= @question.sub_genre.subgenrename %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @question.sub_genre.genre.genrename %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<% else %>
<%= current_user.inspect %>
<p id="notice"><%= notice %></p>
<%= form_for(@question) do |f| %>
<p>
  <strong>Ques:</strong>
  <%= label_tag(@question.ques)%>
</p>


<p>
  <div class="radio-checkbox">
  <strong>Opta:</strong>
  <%=check_box_tag(:Opta, "false")%>
  <%= label_tag(:Opta_false, @question.optA) %>
  </div>
</p>

<p>
  <strong>Optb:</strong>
  <%=check_box_tag(:Optb, "false")%>
  <%= label_tag(:Optb_false, @question.optB) %>
</p>

<p>
  <strong>Optc:</strong>
  <%=check_box_tag(:Optc, "false")%>
  <%= label_tag(:Optc_false, @question.optC) %>
</p>

<p>
  <strong>Optd:</strong>
   <%=check_box_tag(:Optd, "false")%>
  <%= label_tag(:Optd_false, @question.optD) %>
</p>

<%= submit_tag("Submit") %>

<%end%>


<%= link_to 'Back', '/questions/' %>
<% end %>