config/routes.rb
Rails.application.routes.draw do
  get 'genre_display', to:"genre_display#new"

  get '/play',   to:'genre_display#show'
  post '/play',  to:'genre_display#check'

  resources :leaderboards
  resources :questions
  resources :sub_genres
  resources :genres
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: "registrations"}

  root 'home#index'

  post '/questions/:id' => 'questions#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_genre.rb
class SubGenre < ApplicationRecord
  belongs_to :genre
end

app/controllers/sub_genres_controller.rb
class SubGenresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sub_genre, only: [:show, :edit, :update, :destroy]

  # GET /sub_genres
  # GET /sub_genres.json
  def index
    @sub_genres = SubGenre.all
  end

  # GET /sub_genres/1
  # GET /sub_genres/1.json
  def show
  end

  # GET /sub_genres/new
  def new
    if current_user.admin == true
        @sub_genre = SubGenre.new
    else
        redirect_to root_path
    end
  end

  # GET /sub_genres/1/edit
  def edit
      if current_user.admin == true
      else
          redirect_to root_path
      end
  end

  # POST /sub_genres
  # POST /sub_genres.json
  def create
    @sub_genre = SubGenre.new(sub_genre_params)

    respond_to do |format|
      if @sub_genre.save
        format.html { redirect_to @sub_genre, notice: 'Sub genre was successfully created.' }
        format.json { render :show, status: :created, location: @sub_genre }
      else
        format.html { render :new }
        format.json { render json: @sub_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_genres/1
  # PATCH/PUT /sub_genres/1.json
  def update
    respond_to do |format|
      if @sub_genre.update(sub_genre_params)
        format.html { redirect_to @sub_genre, notice: 'Sub genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_genre }
      else
        format.html { render :edit }
        format.json { render json: @sub_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_genres/1
  # DELETE /sub_genres/1.json
  def destroy
    @sub_genre.destroy
    respond_to do |format|
      format.html { redirect_to sub_genres_url, notice: 'Sub genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_genre
      @sub_genre = SubGenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_genre_params
      params.require(:sub_genre).permit(:subgenrename, :genre_id)
    end
end

app/helpers/sub_genres_helper.rb
module SubGenresHelper
end

app/views/sub_genres/_form.html.erb
<%= form_with(model: sub_genre, local: true) do |form| %>
  <% if sub_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_genre.errors.count, "error") %> prohibited this sub_genre from being saved:</h2>

      <ul>
      <% sub_genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subgenrename %>
    <%= form.text_field :subgenrename, id: :sub_genre_subgenrename %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.text_field :genre_id, id: :sub_genre_genre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_genres/edit.html.erb
<h1>Editing Sub Genre</h1>

<%= render 'form', sub_genre: @sub_genre %>

<%= link_to 'Show', @sub_genre %> |
<%= link_to 'Back', sub_genres_path %>

app/views/sub_genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Genres</h1>

<table>
  <thead>
    <tr>
      <th>Subgenrename</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_genres.each do |sub_genre| %>
      <tr>
        <td><%= sub_genre.subgenrename %></td>
        <td><%= sub_genre.genre.genrename %></td>
        <td><%= link_to 'Show', sub_genre %></td>
        <td><%= link_to 'Edit', edit_sub_genre_path(sub_genre) %></td>
        <td><%= link_to 'Destroy', sub_genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Genre', new_sub_genre_path %>

app/views/sub_genres/new.html.erb
<h1>New Sub Genre</h1>

<%= render 'form', sub_genre: @sub_genre %>

<%= link_to 'Back', sub_genres_path %>

app/views/sub_genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subgenrename:</strong>
  <%= @sub_genre.subgenrename %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @sub_genre.genre.genrename %>
</p>

<%= link_to 'Edit', edit_sub_genre_path(@sub_genre) %> |
<%= link_to 'Back', sub_genres_path %>